version: "3.8"

services:
  web:
    build:
      context: .
      args:
        - DATABASE_URI=${DATABASE_URI}
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend-network
    depends_on:
      - db
    user: root
    command: /app/start.sh

  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend-network:
    name: backend-network

volumes:
  postgres_data: