version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend-network
    depends_on:
      - db
    user: root
    command: /app/start.sh

  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-certbot
    restart: unless-stopped
    volumes:
      - nginx-logs:/var/log/nginx/
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/:/etc/nginx/user_conf.d/
    depends_on:
      - web
      - dozzle
    networks:
      - backend-network
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env

  dozzle:
    image: "amir20/dozzle"
    ports:
      - "8080:8080"
    networks:
      - backend-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  backend-network:
    name: backend-network

volumes:
  postgres_data:
  nginx_secrets:
  nginx-logs: