name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.GHA_SSH_HOST}}
          key: ${{secrets.GHA_SSH_PRIVATE_KEY}}
          username: ${{secrets.GHA_SSH_USERNAME}}
          script: |
            cd /home/${{secrets.GHA_SSH_USERNAME}}/levers-assignment
            git pull
            docker compose --env-file .env up --build -d
